services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # 👈 Se agrega esto para verificar si PostgreSQL está listo
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    networks:
      - app_network

  api:
    build: ./api
    container_name: node_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy  # 👈 La API solo se ejecutará cuando PostgreSQL esté listo
    environment:
      DB_HOST: postgres_container
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: "5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
