# Usar una imagen oficial de Node.js
FROM node:18

# Definir el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Exponer el puerto del servicio de autenticación
EXPOSE 4000

# Ejecutar el servicio de autenticación
CMD ["node", "auth.js"]
